package genpact.drltest;

import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class User implements java.io.Serializable {

	private boolean locked;
	private boolean isNew;
	private Date accessTime;
	private int visitCount;
	private String name;

	public boolean isLocked() {
		return locked;
	}

	public void setLocked(boolean locked) {
		this.locked = locked;
	}

	public boolean isNew() {
		return isNew;
	}

	public void setNew(boolean isNew) {
		this.isNew = isNew;
	}

	public Date getAccessTime() {
		return accessTime;
	}

	public void setAccessTime(Date accessTime) {
		this.accessTime = accessTime;
	}

	public int getVisitCount() {
		return visitCount;
	}

	public void setVisitCount(int visitCount) {
		this.visitCount = visitCount;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	static final long serialVersionUID = 1L;

	public User() {
	}

	@Override
	public String toString() {
		return "User [locked=" + locked + ", isNew=" + isNew + ", accessTime=" + accessTime + ", visitCount=" + visitCount + ", name=" + name + "]";
	}

}